apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: taskmate
build:
  local:
    push: false
  artifacts:
    - image: ugoezeh/taskmateauth
      context: taskAuth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ugoezeh/taskmateclient
      context: taskClient
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ugoezeh/taskmatemanager
      context: taskManager
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ugoezeh/taskmatequery
      context: taskQuery
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
manifests:
  rawYaml:
    - ./infra/k8s/*.y*ml
