apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmatequery-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmatequery
  template:
    metadata:
      labels:
        app: taskmatequery
    spec:
      containers:
        - name: taskmatequery
          image: ugoezeh/taskmatequery:latest
          env:
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: COOKIE_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: JWT_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: NATS_CLUSTER_ID
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: NATS_URL
            - name: TASKMATE_QUERY_DB_URI
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: TASKMATE_QUERY_DB_URI
            - name: TASKMATE_QUERY_DB_URI_TEST
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: TASKMATE_QUERY_DB_URI_TEST
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: taskmatequery-srv
  labels:
    app: taskmatequery
spec:
  selector:
    app: taskmatequery
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
