apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmateauth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmateauth
  template:
    metadata:
      labels:
        app: taskmateauth
    spec:
      containers:
        - name: taskmateauth
          image: ugoezeh/taskmateauth:latest
          env:
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: COOKIE_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: JWT_SECRET
            - name: TASKMATE_AUTH_DB_URI
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: TASKMATE_AUTH_DB_URI
            - name: TASKMATE_AUTH_DB_URI_TEST
              valueFrom:
                secretKeyRef:
                  name: taskmate-secrets
                  key: TASKMATE_AUTH_DB_URI_TEST
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: taskmateauth-srv
  labels:
    app: taskmateauth
spec:
  selector:
    app: taskmateauth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
