apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmateclient-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmateclient
  template:
    metadata:
      labels:
        app: taskmateclient
    spec:
      containers:
        - name: taskmateclient
          image: ugoezeh/taskmateclient:latest
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: taskmateclient-srv
  labels:
    app: taskmateclient
spec:
  selector:
    app: taskmateclient
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
